<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VBPGE_Easy_Soccer_Game</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
	  <OptionExplicit>On</OptionExplicit>
	  <OptionStrict>On</OptionStrict>
	  <OptionInfer>On</OptionInfer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VbPixelGameEngine">
      <HintPath>vbPixelGameEngine.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
